### ISSUE TITLE
Is payment_channel private?

### ISSUE THREAD

**Issue by inkredabull** [Open-Rights-Exchange/protocol#1]
Was trying to take the cli for a spin when I ran into these...

```
➜  protocol git:(master) yarn run demo
yarn run v1.6.0
$ node --trace-warnings cli/example.js
module.js:529
    throw err;
    ^
Error: Cannot find module 'core-js'
```

Seeing core-js in package.json, I ran npm install, which failed:

```
➜  protocol git:(master) npm install
...
npm ERR! /usr/local/bin/git ls-remote -h -t https://github.com/api-market/payment_channel.git
npm ERR! fatal: repository 'https://github.com/api-market/payment_channel.git/' not found
```

CC @blackwatertepes

**Comment by blackwatertepes** [comment]
You are correct, sir. The payment channel repository is, indeed, private. And with that, this demo only functions from end-to-end by those with access to the private repos. However, that library, this one, and several others are still under heavy development. They'll all be made public once we have them in a more stable state.
